### ISSUE TITLE
Improve anti-aliasing

### ISSUE THREAD

**Issue by bendenoz** [tipam/pi3d#172]
Hi, first of all thanks for this great library.

Could you add, may be as an option, the EGL_SAMPLES to the attribute list in the Display initialization?
They are using it in the raspberry pi vc sample apps (eg. hello_teapot), and I see a noticeable improvement to the resolution when using it.

check https://github.com/bendenoz/pi3d/commit/e5c4dc18bca719a5f71605cd5c9ee685842fa48f for an example.

Thanks

**Comment by paddywwoof** [comment]
Thanks, that's excellent, doesn't seem to slow the rendering down and will definitley add it, but might make it overridable as with DEPTH
