### ISSUE TITLE
Change light color 

### ISSUE THREAD

**Issue by mikolaskova** [tipam/pi3d#179]
Hello,

I want to change the light properties f.e. color or position  when pressing a certain key.
I tried in the ShadowCast example, adding a new key 'l'
...
elif k==108:  #key l
     mylight.color(lightcol=(1.0, 0.0, 0.0))
...
nothing happens. Do I have to add some code to somehow refresh the Scene or did I understand the usage of the color method (of the pi3d.Light-Object) wrongly?
Or is there an example where the lights are switched on/of, moved or changed somehow by the user?

(pressing the l-key and doing something else works well)

Thanks and regards

Adriana

**Comment by paddywwoof** [comment]
The light info is actually held in the Shape object. (Nearly everything that is passed to the Shader is held in Shape, Buffer, Camera or Shader objects)

The Amazing.py demo shows how the Light properties are updated to a Shape using the set_light() method, see also http://pi3d.github.io/html/pi3d.html#module-pi3d.Light and http://pi3d.github.io/html/_modules/pi3d/Shape.html#Shape.set_light
