### ISSUE TITLE
Demos try and access /dev/input/mice

### ISSUE THREAD

**Issue by stuaxo** [tipam/pi3d#181]
I get permissions problems trying because the demos try and access /dev/input/mice  is the a different API this could use. 

(Note - running on laptop, not pi)

**Comment by paddywwoof** [comment]
Yes, running on Ubuntu you will have to start apps with sudo. On Windows the mouse info is got via pygame as the whole  /dev/input/ system doesn't exist! I will clarify this in the readme

**Comment by stuaxo** [comment]
Is there a way I can make it use pygame in ubuntu, as I like to use virtualenv, and not keen on sudo ?
