### ISSUE TITLE
Handle errors / detached devices in EventStream

### ISSUE THREAD

**Issue by buxit** [tipam/pi3d#199]
when detaching an input device during runtime the system hangs in EventStream.allNext() which is called from do_input_events().

**Comment by paddywwoof** [comment]
@buxit, thanks for the pointer I will have a look at that. It's a long time since I peered inside the events system, but as a generalization it maybe cleaner and faster to use a try/catch than check devices each do_input_events()

**Comment by buxit** [comment]
here's my idea on how to fix this: #200

**Comment by paddywwoof** [comment]
hopefully fixed - pulled into pi3d anyway!
