### ISSUE TITLE
Integrate with gstreamer (reprise) ?

### ISSUE THREAD

**Issue by stuaxo** [tipam/pi3d#205]
As an output of the conversation here
https://github.com/tipam/pi3d/issues/203

I've managed to get gstreamer to output to a dispmanx window I created, using set_window_handle

https://gist.github.com/stuaxo/3009b761cba1085ac5730c7485506ee4

Now I have a this, is it possible to use this with pi3d, to do stuff like apply shaders, or even use it a video texture somehow ?

At the least, I would like to use pi3d to draw overlays over the top, e.g.  an empty battery sign, but certainly being able to apply shaders etc would be great if I could effect the output with shaders.

**Comment by paddywwoof** [comment]
You might be able to disable the part of pi3d/util/DisplayOpenGL.py that does the same native window creation and pass the handle to pi3d from your glstreamer code. However I imagine that there might be issues updating the same surface by two agents. If you want to use the video as a Texture then I think it would be easier to use the method in swehner's foos. You can create a second (and more) display surface for pi3d to draw onto that will be in front of other surfaces.

**Comment by stuaxo** [comment]
I'll have a look into these, cheers :)
