### ISSUE TITLE
Display x and y position not respected using xlib.  

### ISSUE THREAD

**Issue by IQA001** [tipam/pi3d#211]
The x and y position of display aren't respected on my system (Ubuntu 14.04).  An additional line in DisplayOpenGL.py calling xlib.XMoveWindow appears to fix the problem (around line 187):

`xlib.XMoveWindow(self.d, self.window, x, y)`
` self.surface = openegl.eglCreateWindowSurface(self.display, self.config, self.window, 0)`

**Comment by paddywwoof** [comment]
Hi, Thanks for that. I'm not sure exactly what the issue is you're suffering from (xy position of mouse relative to window?) but adding that line doesn't seem to cause a problem on this laptop (ubuntu 16.04) so I will commit it to the develop branch and push to github.
