### ISSUE TITLE
exit

### ISSUE THREAD

**Issue by tekcomm** [tipam/pi3d#218]

**Comment by rec** [comment]
We'll need more information than this to continue!  :-)

**Comment by tekcomm** [comment]
root@AMD-rocm-rippa:/home/guru# dmesg | grep amd
[    1.105708] [drm] amdgpu kernel modesetting enabled.
[    1.125128] fb: switching to amdgpudrmfb from EFI VGA
[    1.127266] amdgpu 0000:01:00.0: Invalid PCI ROM header signature:
expecting 0xaa55, got 0xffff
[    1.127338] amdgpu 0000:01:00.0: BAR 2: releasing [mem
0xe0000000-0xe01fffff 64bit pref]
[    1.127341] amdgpu 0000:01:00.0: BAR 0: releasing [mem
0xd0000000-0xdfffffff 64bit pref]
[    1.127363] amdgpu 0000:01:00.0: BAR 0: assigned [mem
0x2000000000-0x21ffffffff 64bit pref]
[    1.127370] amdgpu 0000:01:00.0: BAR 2: assigned [mem
0x2200000000-0x22001fffff 64bit pref]
[    1.127394] amdgpu 0000:01:00.0: VRAM: 8192M 0x000000F400000000 -
0x000000F5FFFFFFFF (8192M used)
[    1.127396] amdgpu 0000:01:00.0: GTT: 256M 0x0000000000000000 -
0x000000000FFFFFFF
[    1.127445] [drm] amdgpu: 8192M of VRAM memory ready
[    1.127447] [drm] amdgpu: 8192M of GTT memory ready.
[    1.865562] [drm] Initialized amdgpu 3.23.0 20150101 for 0000:01:00.0 on
minor 0
[    1.865596] amdgpu 0000:05:00.0: enabling device (0000 -> 0003)
[    2.940308] amdgpu 0000:05:00.0: BAR 2: releasing [mem
0x2ff0000000-0x2ff01fffff 64bit pref]
[    2.940311] amdgpu 0000:05:00.0: BAR 0: releasing [mem
0x2fe0000000-0x2fefffffff 64bit pref]
[    2.940347] amdgpu 0000:05:00.0: BAR 0: assigned [mem
0x2400000000-0x25ffffffff 64bit pref]
[    2.940358] amdgpu 0000:05:00.0: BAR 2: assigned [mem
0x2300000000-0x23001fffff 64bit pref]
[    2.940392] amdgpu 0000:05:00.0: VRAM: 8192M 0x000000F400000000 -
0x000000F5FFFFFFFF (8192M used)
[    2.940394] amdgpu 0000:05:00.0: GTT: 256M 0x0000000000000000 -
0x000000000FFFFFFF
[    2.940406] [drm] amdgpu: 8192M of VRAM memory ready
[    2.940408] [drm] amdgpu: 8192M of GTT memory ready.
[    3.658624] [drm] Initialized amdgpu 3.23.0 20150101 for 0000:05:00.0 on
minor 1
root@AMD-rocm-rippa:/home/guru# cl
clear          clear_console  clinfo
root@AMD-rocm-rippa:/home/guru# cl
clear          clear_console  clinfo
root@AMD-rocm-rippa:/home/guru# clinfo
Number of platforms:  1
  Platform Profile:  FULL_PROFILE
  Platform Version:  OpenCL 2.1 AMD-APP (2527.3)
  Platform Name:  AMD Accelerated Parallel Processing
  Platform Vendor:  Advanced Micro Devices, Inc.
  Platform Extensions:  cl_khr_icd cl_amd_event_callback
cl_amd_offline_devices


  Platform Name:  AMD Accelerated Parallel Processing
Number of devices:  2
  Device Type:  CL_DEVICE_TYPE_GPU
  Vendor ID:  1002h
  Board name:  Radeon RX 570 Series
  Device Topology:  PCI[ B#1, D#0, F#0 ]
  Max compute units:  32
  Max work items dimensions:  3
    Max work items[0]:  1024
    Max work items[1]:  1024
    Max work items[2]:  1024
  Max work group size:  256
  Preferred vector width char:  4
  Preferred vector width short:  2
  Preferred vector width int:  1
  Preferred vector width long:  1
  Preferred vector width float:  1
  Preferred vector width double:  1
  Native vector width char:  4
  Native vector width short:  2
  Native vector width int:  1
  Native vector width long:  1
  Native vector width float:  1
  Native vector width double:  1
  Max clock frequency:  1150Mhz
  Address bits:  64
  Max memory allocation:  4244635648
  Image support:  Yes
  Max number of images read arguments:  128
  Max number of images write arguments:  8
  Max image 2D width:  16384
  Max image 2D height:  16384
  Max image 3D width:  2048
  Max image 3D height:  2048
  Max image 3D depth:  2048
  Max samplers within kernel:  16
  Max size of kernel argument:  1024
  Alignment (bits) of base address:  2048
  Minimum alignment (bytes) for any datatype:  128
  Single precision floating point capability
    Denorms:  No
    Quiet NaNs:  Yes
    Round to nearest even:  Yes
    Round to zero:  Yes
    Round to +ve and infinity:  Yes
    IEEE754-2008 fused multiply-add:  Yes
  Cache type:  Read/Write
  Cache line size:  64
  Cache size:  16384
  Global memory size:  5746974720
  Constant buffer size:  4244635648
  Max number of constant args:  8
  Local memory type:  Scratchpad
  Local memory size:  32768
  Max pipe arguments:  0
  Max pipe active reservations:  0
  Max pipe packet size:  0
  Max global variable size:  0
  Max global variable preferred total size:  0
  Max read/write image args:  0
  Max on device events:  0
  Queue on device max size:  0
  Max on device queues:  0
  Queue on device preferred size:  0
  SVM capabilities:
    Coarse grain buffer:  No
    Fine grain buffer:  No
    Fine grain system:  No
    Atomics:  No
  Preferred platform atomic alignment:  0
  Preferred global atomic alignment:  0
  Preferred local atomic alignment:  0
  Kernel Preferred work group size multiple:  64
  Error correction support:  0
  Unified memory for Host and Device:  0
  Profiling timer resolution:  1
  Device endianess:  Little
  Available:  Yes
  Compiler available:  Yes
  Execution capabilities:
    Execute OpenCL kernels:  Yes
    Execute native function:  No
  Queue on Host properties:
    Out-of-Order:  No
    Profiling :  Yes
  Queue on Device properties:
    Out-of-Order:  No
    Profiling :  No
  Platform ID:  0x7f3d43c0d510
  Name:  Ellesmere
  Vendor:  Advanced Micro Devices, Inc.
  Device OpenCL C version:  OpenCL C 1.2
  Driver version:  2527.3
  Profile:  FULL_PROFILE
  Version:  OpenCL 1.2 AMD-APP (2527.3)
  Extensions:  cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics
cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics
cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics
cl_khr_int64_extended_atomics cl_khr_3d_image_writes
cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing
cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops
cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir
cl_khr_gl_event


  Device Type:  CL_DEVICE_TYPE_GPU
  Vendor ID:  1002h
  Board name:  Radeon RX 570 Series
  Device Topology:  PCI[ B#5, D#0, F#0 ]
  Max compute units:  32
  Max work items dimensions:  3
    Max work items[0]:  1024
    Max work items[1]:  1024
    Max work items[2]:  1024
  Max work group size:  256
  Preferred vector width char:  4
  Preferred vector width short:  2
  Preferred vector width int:  1
  Preferred vector width long:  1
  Preferred vector width float:  1
  Preferred vector width double:  1
  Native vector width char:  4
  Native vector width short:  2
  Native vector width int:  1
  Native vector width long:  1
  Native vector width float:  1
  Native vector width double:  1
  Max clock frequency:  1150Mhz
  Address bits:  64
  Max memory allocation:  4244635648
  Image support:  Yes
  Max number of images read arguments:  128
  Max number of images write arguments:  8
  Max image 2D width:  16384
  Max image 2D height:  16384
  Max image 3D width:  2048
  Max image 3D height:  2048
  Max image 3D depth:  2048
  Max samplers within kernel:  16
  Max size of kernel argument:  1024
  Alignment (bits) of base address:  2048
  Minimum alignment (bytes) for any datatype:  128
  Single precision floating point capability
    Denorms:  No
    Quiet NaNs:  Yes
    Round to nearest even:  Yes
    Round to zero:  Yes
    Round to +ve and infinity:  Yes
    IEEE754-2008 fused multiply-add:  Yes
  Cache type:  Read/Write
  Cache line size:  64
  Cache size:  16384
  Global memory size:  5746974720
  Constant buffer size:  4244635648
  Max number of constant args:  8
  Local memory type:  Scratchpad
  Local memory size:  32768
  Max pipe arguments:  0
  Max pipe active reservations:  0
  Max pipe packet size:  0
  Max global variable size:  0
  Max global variable preferred total size:  0
  Max read/write image args:  0
  Max on device events:  0
  Queue on device max size:  0
  Max on device queues:  0
  Queue on device preferred size:  0
  SVM capabilities:
    Coarse grain buffer:  No
    Fine grain buffer:  No
    Fine grain system:  No
    Atomics:  No
  Preferred platform atomic alignment:  0
  Preferred global atomic alignment:  0
  Preferred local atomic alignment:  0
  Kernel Preferred work group size multiple:  64
  Error correction support:  0
  Unified memory for Host and Device:  0
  Profiling timer resolution:  1
  Device endianess:  Little
  Available:  Yes
  Compiler available:  Yes
  Execution capabilities:
    Execute OpenCL kernels:  Yes
    Execute native function:  No
  Queue on Host properties:
    Out-of-Order:  No
    Profiling :  Yes
  Queue on Device properties:
    Out-of-Order:  No
    Profiling :  No
  Platform ID:  0x7f3d43c0d510
  Name:  Ellesmere
  Vendor:  Advanced Micro Devices, Inc.
  Device OpenCL C version:  OpenCL C 1.2
  Driver version:  2527.3
  Profile:  FULL_PROFILE
  Version:  OpenCL 1.2 AMD-APP (2527.3)
  Extensions:  cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics
cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics
cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics
cl_khr_int64_extended_atomics cl_khr_3d_image_writes
cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing
cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops
cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir
cl_khr_gl_event


root@AMD-rocm-rippa:/home/guru# uname -a
Linux AMD-rocm-rippa 4.16.0-041600rc7-generic #201803252030 SMP Mon Mar 26
00:32:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@AMD-rocm-rippa:/home/guru# cd
root@AMD-rocm-rippa:~# ls
amdcovc     amdtweak-master  Claymore  fah       HelloWorld
 installnvidiasupport.sh  nohup.out          QuantumRNG  sgminer
 start-oc.sh       start-rtminer.sh
amdgpu-pro  atiflash         ethminer  fahtmpfs  HelloWorld.cl
installvegasupport.sh    PolarisBiosEditor  r8168       start-net.sh
start-rtlinux.sh  start.sh
root@AMD-rocm-rippa:~# cd /home
root@AMD-rocm-rippa:/home# cd guru/
root@AMD-rocm-rippa:/home/guru# ls
add2bashrc         linux-headers-4.16.0-041600rc
7_4.16.0-041600rc7.201803252030_all.deb            text-mode-fonts
clean-myself.bash  linux-headers-4.16.0-041600rc7
-generic_4.16.0-041600rc7.201803252030_amd64.deb  text-mode-installer
fontlist           linux-image-4.16.0-041600rc7-
generic_4.16.0-041600rc7.201803252030_amd64.deb    text-mode-menu
l                  r8168-dkms_8.045.08-2_all.deb
                       truncate-log

Attached is the kernel version to try
​
 linux-headers-4.16.0-041600rc7-generic_4.16.0-0...
<https://drive.google.com/file/d/1hdaPRU02W8GLP5e1ib35Fzb-FXtX5w9t/view?usp=drive_web>
​​
 linux-headers-4.16.0-041600rc7_4.16.0-041600rc7...
<https://drive.google.com/file/d/1qKAcyZx52z8c1MfeZz-gIX7JxSacFemv/view?usp=drive_web>
​​
 linux-image-4.16.0-041600rc7-generic_4.16.0-041...
<https://drive.google.com/file/d/1bstQ1wHZYDRh3Xszt3P7KuwmJ22jsBbb/view?usp=drive_web>
​​
 r8168-dkms_8.045.08-2_all.deb
<https://drive.google.com/file/d/17hQJu6EpTaJpoqGAK2artxx3Ie7NA7O-/view?usp=drive_web>
​

**Comment by rec** [comment]
By "more information" I mean that you haven't actually told us what your issue _is._

**Comment by tekcomm** [comment]
Hahhaha, This is called sleep derpervation, I had a issue with the I7 Gen3 support it was a issues related to grub.

**Comment by tekcomm** [comment]
I posted the fix for other intel board users I tested it up to the 4.17 prerelease

**Comment by tekcomm** [comment]
I am so used to being in terminal mode after 40 years I was 1/2 sleep and typed, You guested it exit LFAO

**Comment by tekcomm** [comment]
Sorry bout that, I was up for like 30+ hours coding and face-palmed
https://github.com/RadeonOpenCompute/ROCm/issues/361 building a live
userland in 2 x 30+ hour coding benders lol

**Comment by rec** [comment]
You will rot your brain that way!!  :-D

**Comment by tekcomm** [comment]
I looked at your code, I can tell you don't practice what ya preach hahahha

**Comment by tekcomm** [comment]
Im like oh look a zombie Apocalypse, click click click,  lol
