### ISSUE TITLE
Display location change

### ISSUE THREAD

**Issue by kunguz** [tipam/pi3d#221]
What is the best way to change the display x y during runtime?

I am hoping  to change the location of a display defined similar to the below code:

    import pi3d
    DISPLAY = pi3d.Display.create(x=0, y=0, use_pygame=True)

Basically my hope is to change location of the display, but what is the best practice here?

    DISPLAY.left += 10
 
does nothing basically...

**Comment by kunguz** [comment]
Closest thing I found doing some changes only in Raspberry Pi, not on a desktop machine is this  definition:

    display.opengl.resize(
                                      x=dict["display"]["offset"][0],
                                      y=dict["display"]["offset"][1],
                                      w=dict["display"]["resolution"][0],
                                      h=dict["display"]["resolution"][1]
                                     )

Funny thing is this is moving the surface but still the content uses initial 0,0 of the screen for rendering


Am I missing something here?

**Comment by paddywwoof** [comment]
I'm away at the moment but will have a look on Tuesday when I'm back. I think the tk wrapper does something (on the pi). generally x or pygame can't specify x y position but might be able to give hints.

**Comment by kunguz** [comment]
I am running on a headless rpi, thus I think tk wrapper may not be an option. Please correct me if I am wrong.

**Comment by paddywwoof** [comment]
@kunguz OK I'm back at a proper computer now and have a rpi to check it on. To get the resize to work you need to alter some of the properties of the Display object (top, left, width, height) This is all done for you if you use the Display.resize() method (which does also call self.opengl.resize()) So in your example try:
```
display.resize(
                          x=dict["display"]["offset"][0],
                          y=dict["display"]["offset"][1],
                          w=dict["display"]["resolution"][0],
                          h=dict["display"]["resolution"][1]
                                 )
```
This seems to do the trick on a couple of quick tests here, let me know if it works for your setup.

On the desktop machine the window is managed externally. I think I've tried to get the x11 server to position windows with little success in the past. With pygame it might be possible to get sdl to set the position and pygame.init() something like https://www.pygame.org/wiki/SettingWindowPosition I will have a look at that later

Paddy

PS if dict is a variable name in you code I would *strongly* suggest changing it to something else. Using 'internal' python symbols potentially confuses people such as me, will confuse you in a few weeks time and stands a chance of confusing the python interpreter itself!
