### ISSUE TITLE
[Question] Axis orientation

### ISSUE THREAD

**Issue by mantielero** [tipam/pi3d#226]
I am a new **pi3d** user. I have a question about axis orientation. 

It looks like **pi3d** is using left handed axis orientation:
- x axis: to the right
- y axis: goes up
- z axis: backwards in the screen

Is this right?

But OpenGL seem to be right handed. Why is that? 

Is there something that I am missing?

Maybe a clarification on the documentation about this topic would be helpful.

**Comment by paddywwoof** [comment]
Yes, I'm not sure why or how pi3d got set that way. At an early stage, and then it became an issue to unscramble without breaking existing applications.

Good idea to make it clearer in the documentation..
