### ISSUE TITLE
Is pi3d compatible with Raspbian Desktop too?

### ISSUE THREAD

**Issue by matteoraggi** [tipam/pi3d#232]
Hi, I would like to know if pi3d will run on Raspbian Desktop too..
https://www.raspberrypi.org/downloads/raspberry-pi-desktop/

**Comment by m4r35n357** [comment]
Well I have tried some reliably working code on the Pi4 (Raspbian) and it certainly does not work for me.

In fact the test code in the README fails in the same manner (freezes silently) as my code.  CTRL-C does not kill it, you need to do CTRL-Z and kill the job.
