### ISSUE TITLE
pi3d and playing videos

### ISSUE THREAD

**Issue by matteoraggi** [tipam/pi3d#234]
H, I love howblending galleries are wonderfull with pi3d. Do you have suggestions to alternate the blending picture transitions with videos (no effect with videos). Should I create a code with omxplayer or are there some tricks or demos ready for it?
Just want to alternate pictures with videos..

**Comment by paddywwoof** [comment]
Hi, not tired it yet but i would run omxplayer as a subprocess on desktop and fade still image to transparent when it had started. start fading next still to opaque when nearly at end.

Did you try PictureFrame_new

**Comment by matteoraggi** [comment]
In the demos I find only PictureFrame.py .. where should I find  PictureFrame_new ?
